repo:
  URL: "https://github.com/peaceiris/hugo-theme-iris"
  branch: master
  contentDir: exampleSite/content

# revealjs code highlight
# highlightStyle: solarized-light

highlightStyle: monokai

themeColor: "#000000" # smart phone's browser tab color

footer:
  copyright:
    year: 2020
    name: Peacock
    link: "https://www.peacock0803sz.com/"

font:
  # URL: "https://fonts.googleapis.com/css?family=Noto+Sans+JP"
  # family: "Noto Sans JP"

icon:
  favicon: /favicon/favicon64.ico
  x180: /favicon/apple-icon-180x180.jpg
  mstile: /favicon/ms-icon-150x150.jpg
