[languages]
  [languages.ja]
    baseURL = "https://peacock0803sz.com"
    languageCode = "ja-jp"
    title = "Peacock"
    theme = "hugo-theme-iris"
    publishDir = "public"
    staticDir = "static"
